// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaYEfp7w1Lvcf0kuHeQu-PfT6VdetLffw',
    appId: '1:1038702303938:web:2788636c3af4eb2592795b',
    messagingSenderId: '1038702303938',
    projectId: 'flutter-assignment-2cd78',
    authDomain: 'flutter-assignment-2cd78.firebaseapp.com',
    databaseURL: 'https://flutter-assignment-2cd78-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-assignment-2cd78.appspot.com',
    measurementId: 'G-YCPDLM2GXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBzJkJnE1rRr1btvo-LE_KeHdB98aL3zE',
    appId: '1:1038702303938:android:55c440b5528af6e192795b',
    messagingSenderId: '1038702303938',
    projectId: 'flutter-assignment-2cd78',
    databaseURL: 'https://flutter-assignment-2cd78-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-assignment-2cd78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3faZffLoG4cvA83jtQ-krH5N3V1RZmsE',
    appId: '1:1038702303938:ios:383386e50509eff792795b',
    messagingSenderId: '1038702303938',
    projectId: 'flutter-assignment-2cd78',
    databaseURL: 'https://flutter-assignment-2cd78-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-assignment-2cd78.appspot.com',
    iosBundleId: 'com.example.flutterAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3faZffLoG4cvA83jtQ-krH5N3V1RZmsE',
    appId: '1:1038702303938:ios:383386e50509eff792795b',
    messagingSenderId: '1038702303938',
    projectId: 'flutter-assignment-2cd78',
    databaseURL: 'https://flutter-assignment-2cd78-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-assignment-2cd78.appspot.com',
    iosBundleId: 'com.example.flutterAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaYEfp7w1Lvcf0kuHeQu-PfT6VdetLffw',
    appId: '1:1038702303938:web:7f36b7229910529092795b',
    messagingSenderId: '1038702303938',
    projectId: 'flutter-assignment-2cd78',
    authDomain: 'flutter-assignment-2cd78.firebaseapp.com',
    databaseURL: 'https://flutter-assignment-2cd78-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-assignment-2cd78.appspot.com',
    measurementId: 'G-564B5PPD7T',
  );
}
