// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMI-Nz_wYdqqR7uq0i65J5YRYLL5adCY4',
    appId: '1:12457094783:web:02b4ffab5a2ab77aa1194a',
    messagingSenderId: '12457094783',
    projectId: 'flutter-assignment-61b40',
    authDomain: 'flutter-assignment-61b40.firebaseapp.com',
    storageBucket: 'flutter-assignment-61b40.appspot.com',
    measurementId: 'G-KV13YK9S2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKKvUS7gAyWxTIdVR3cKywY9jwKtI6uKg',
    appId: '1:12457094783:android:f5dc2b4a5e9a641da1194a',
    messagingSenderId: '12457094783',
    projectId: 'flutter-assignment-61b40',
    storageBucket: 'flutter-assignment-61b40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3UhIXCssvpJJfZUh1QXPXdzOSDOmrfHA',
    appId: '1:12457094783:ios:aeded09225508766a1194a',
    messagingSenderId: '12457094783',
    projectId: 'flutter-assignment-61b40',
    storageBucket: 'flutter-assignment-61b40.appspot.com',
    iosClientId:
        '12457094783-7us38lqd0ookrhqeebcu0j2cts7ubhco.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3UhIXCssvpJJfZUh1QXPXdzOSDOmrfHA',
    appId: '1:12457094783:ios:aeded09225508766a1194a',
    messagingSenderId: '12457094783',
    projectId: 'flutter-assignment-61b40',
    storageBucket: 'flutter-assignment-61b40.appspot.com',
    iosClientId:
        '12457094783-7us38lqd0ookrhqeebcu0j2cts7ubhco.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMI-Nz_wYdqqR7uq0i65J5YRYLL5adCY4',
    appId: '1:12457094783:web:251a4987f0e2e7d2a1194a',
    messagingSenderId: '12457094783',
    projectId: 'flutter-assignment-61b40',
    authDomain: 'flutter-assignment-61b40.firebaseapp.com',
    storageBucket: 'flutter-assignment-61b40.appspot.com',
    measurementId: 'G-077C7L0D4Y',
  );
}
